export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_SUCEESS = "SET_REGISTER_CUSTOMER";
export const SET_USER = "SET_USER";
export const SET_EORROR = "SET_EORROR";  
// export const Base_URL = "http://212.129.7.174/api";
export const Base_URL = "http://10.10.10.122:8000/api";
export const GET_HISTORY_DATA = "GET_HISTORY_DATA";
export const CHANGE_SUCCESS = "CHANGE_SUCCESS";
export const CHANGE_ERROR = "CHANGE_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_ERRORS = "LOGIN_ERRORS";
export const REGISTER_SUCEESS = "REGISTER_SUCEESS";
export const REGISTER_ERRORS = "REGISTER_ERRORS";
export const PROFILE_REGISTER_SUCCESS = "PROFILE_REGISTER_SUCCESS";
export const PROFILE_REGISTER_ERROR = "PROFILE_REGISTER_ERROR";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
    


// export const IMAGE_PATH = "http://212.129.7.174:3000/assets/img/";
export const IMAGE_PATH = "http://localhost:3000/assets/img/";

// export const IMAGE_PATH_UPLOAD = "http://212.129.7.174";
export const IMAGE_PATH_UPLOAD = "http://10.10.10.122:8000";

export const FIRE_REGISTER_SUCEESS = "FIRE_REGISTER_SUCEESS";




// Pup part

export const GET_DASH_DATA_SUCCESS = "GET_DASH_DATA_SUCCESS";
export const GET_DASH_DATA_ERROR = "GET_DASH_DATA_ERROR";
export const GET_PUP_SUCCESS = "GET_PUP_SUCCESS";
export const GET_PUP_ERROR = "GET_PUP_ERROR";
export const GET_PUP_SAVE_SUCCESS = "GET_PUP_SAVE_SUCCESS";
export const GET_PUP_EDIT_SUCCESS = "GET_PUP_EDIT_SUCCESS";
export const GET_PUP_EDIT_ERROR = "GET_PUP_EDIT_ERROR";
export const GET_PUP_DETAIL_SUCCESS = "GET_PUP_DETAIL_SUCCESS";
export const GET_PUP_DETAIL_ERROR = "GET_PUP_DETAIL_ERROR";
export const GET_PUP_EDIT_DATA_SUCCESS = "GET_PUP_EDIT_DATA_SUCCESS";
export const GET_PUP_EDIT_DATA_ERROR = "GET_PUP_EDIT_DATA_ERROR";
export const PUP_DELETE_SUCCESS = "PUP_DELETE_SUCCESS";
export const PUP_STATUS_EDIT_SUCCESS = "PUP_STATUS_EDIT_SUCCESS";
export const GET_BREED_DATA_SUCCESS = "GET_BREED_DATA_SUCCESS";
export const GET_BREED_DATA_ERROR = "GET_BREED_DATA_ERROR";
    





export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_ERROR = "GET_REVIEWS_ERROR";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_ERROR = "GET_CUSTOMER_ERROR";
export const GET_DELETE_CUSTOMER_SUCCESS = "GET_DELETE_CUSTOMER_SUCCESS";
export const GET_CREATE_CUSTOMER_SUCCESS = "GET_CREATE_CUSTOMER_SUCCESS";


// Client 
export const GET_CLIENT_PUP_READ_SUCCESS = "GET_CLIENT_PUP_READ_SUCCESS";
export const GET_CLIENT_PUP_READ_ERROR = "GET_CLIENT_PUP_READ_ERROR";
export const GET_CLIENT_REVIEW_READ_SUCCESS = "GET_CLIENT_REVIEW_READ_SUCCESS";
export const GET_CLIENT_REVIEW_READ_ERROR = "GET_CLIENT_REVIEW_READ_ERROR";
export const GET_CLIENT_REVIEW_ADD_SUCCESS = "GET_CLIENT_REVIEW_ADD_SUCCESS";
export const GET_CLIENT_REVIEW_ADD_ERROR = "GET_CLIENT_REVIEW_ADD_ERROR";
export const GET_CLIENT_DETAIL_SUCCESS = "GET_CLIENT_DETAIL_SUCCESS";
export const GET_CLIENT_DETAIL_ERROR = "GET_CLIENT_DETAIL_ERROR";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_SHIPPING_INFO_ERROR = "GET_SHIPPING_INFO_ERROR";
export const GET_SHIPPING_INFO_SUCCESS = "GET_SHIPPING_INFO_SUCCESS";
